### ISSUE TITLE
Build SP1 with AVX512 - 2x speedup.

### ISSUE THREAD

**Issue by mratsim** [a16z/zkvm-benchmarks#1]
In our benchmarks, SP1 can get a 2x perf improvement by compiling it with AVX512 on supporting CPUs.

See https://github.com/succinctlabs/sp1/pull/488

This means adding this to rust flags:

```
RUSTFLAGS='-C target_feature=+avx512ifma,+avx512vl --cfg curve25519_dalek_backend="simd"
```

**Comment by jtguibas** [comment]
Wow, amazing!!!

**Comment by jtguibas** [comment]
I will add this to the README.

**Comment by moodlezoup** [comment]
We already have `-C target-cpu=native` https://github.com/a16z/zkvm-benchmarks/blob/master/Makefile#L11
so we just need to add ` --cfg curve25519_dalek_backend="simd"` ?
Also what is SP1 using curve25519 for?

**Comment by mratsim** [comment]
Ah, misread the PR, the feature flag is `--nightly-features` for Plonky3, see https://github.com/Plonky3/Plonky3/pull/275

**Comment by dyxushuai** [comment]
AVX512 must be able by feature `nightly-features`, so you can update the sp1 to the newest with
```
p3-baby-bear = { git = "https://github.com/Plonky3/Plonky3.git", branch = "sp1", features = [
    "nightly-features",
] }
```
or add a flag to cargo
```
cd sp1 && RUSTFLAGS="-C target-cpu=native" cargo run --release --features nightly-features
```
